### ISSUE TITLE
search term highlight setting for PrettyFunctional

### ISSUE THREAD

**Issue by DivineDominion** [Zettelkasten-Method/The-Archive-Themes#2]
@NSSynapse: I noticed that search highlights are not being supported by your theme at the moment:

https://github.com/Zettelkasten-Method/The-Archive-Themes/blob/5f5e24a8c3468429389da6b7062b918742853c01/Themes/PrettyFunctional%20(Basic).theme.json#L12

Here's a sample from _Solarized (Light)_ and how the colors compare to actual active selections:

```
       "highlight": {
            "backgroundColor": "#eee8d5",
            "unfocusedBackgroundColor": "#dbdcce"
        },
        "selection": {
            "color": "#fdf6e3",
            "backgroundColor": "#d33682",
            "unfocusedBackgroundColor": "#e35db5"
        }
```

Users can disable this feature, but if they do enable it, themes should support that consistently. Can you figure out `highlight` colors that do not suck? :)

**Comment by NSSynapse** [comment]
Good call. I prefer "Highlight search terms in the editor" to be turned off, so I totally missed that highlights were invisible with my theme. I just created a pull request for an updated version of the theme.

**Comment by DivineDominion** [comment]
Great, thanks!
